# .travis.yml
#
# This source file is part of the Workspace open source project.
#
# Copyright Â©2017 Jeremy David Giesbrecht and the Workspace contributors.
#
# Soli Deo gloria
#
# Licensed under the Apache License, Version 2.0
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

language: generic
matrix:
  include:
    - os: osx
    - os: linux
      env: SWIFT_VERSION=3.0.2
osx_image: xcode8.2
dist: trusty
script: "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\"; swift test"