# .travis.yml
#
# This source file is part of the Workspace open source project.
#
# Copyright Â©2017 Jeremy David Giesbrecht and the Workspace contributors.
#
# Soli Deo gloria
#
# Licensed under the Apache License, Version 2.0
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

# !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!!
# This file is managed by Workspace.
# Manual changes will not persist.
# For more information, see:
# https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Continuous Integration.md
# !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!!

language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
    - os: linux
      dist: trusty
      env: SWIFT_VERSION=3.0.2
      script: "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\"; bash ./Refresh\\\ Workspace\\\ \\(macOS\\).command; bash ./Validate\\\ Changes\\\ \\(macOS\\).command"
