# .travis.yml
#
# This source file is part of the Workspace open source project.
# https://github.com/SDGGiesbrecht/Workspace#workspace
#
# Copyright Â©2017 Jeremy David Giesbrecht and the Workspace project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

language: generic
matrix:
  include:

cache:
  directories:
  - $HOME/Library/Caches/ca.solideogloria.Workspace
  - $HOME/.cache/ca.solideogloria.Workspace
